import OpenAI from "openai";

// Initialize Groq (via OpenAI SDK) lazily
const getAiClient = () => {
    // @ts-ignore
    const apiKey = import.meta.env.VITE_GROQ_API_KEY || '';
    if (!apiKey) return null;

    return new OpenAI({
        apiKey: apiKey,
        baseURL: "https://api.groq.com/openai/v1",
        dangerouslyAllowBrowser: true // Required for client-side usage
    });
};

export const generateMusicInsights = async (contextData: string): Promise<string> => {
  try {
    const client = getAiClient();
    if (!client) return "Configure VITE_GROQ_API_KEY to see insights.";

    const prompt = `
      You are a music analytics expert. Analyze the following data summary and provide a concise, 
      Apple Music-style "Editor's Note" or strategic insight about the listening trends.
      Keep it short, encouraging, and professional (max 2 sentences).
      
      Data: ${contextData}
    `;

    const response = await client.chat.completions.create({
        model: "llama-3.3-70b-versatile",
        messages: [{ role: "user", content: prompt }],
        temperature: 0.7
    });
    
    return response.choices[0]?.message?.content || "No insights available via Groq.";
  } catch (error) {
    console.error("Groq API Error:", error);
    return "Unable to generate insights right now.";
  }
};

export const generateDynamicCategoryQuery = async (availableGenres: string[]): Promise<any> => {
    try {
        const client = getAiClient();
        if (!client) throw new Error("No API Key");

        const hour = new Date().getHours();
        const timeOfDay = hour < 12 ? 'morning' : hour < 18 ? 'afternoon' : 'night';

        const prompt = `
            You are a music curator for a personal dashboard.
            Your goal is to invent a creative, specific chart category based on a filter criteria.
            The user has a database of listening history.
            
            Current context:
            - Time of day: ${timeOfDay}
            - Available Genres in library: ${availableGenres.join(', ')}
            
            Generate a JSON object defining a creative category and how to filter for it.
            
            Constraint:
            - "filterType" must be one of: "time", "genre", "keyword".
            - If "filterType" is "time", provide "startHour" and "endHour" (0-23).
            - If "filterType" is "genre", provide "genreKeyword" (string).
            - If "filterType" is "keyword", provide "keyword" (to match in track/artist name).
            
            Return JSON only:
            {
                "title": "Creative Category Title (e.g. Late Night Vibes)",
                "description": "Short description (e.g. Tracks played after midnight)",
                "filterType": "time",
                "filterParams": { "startHour": 0, "endHour": 4 }
            }
        `;

        const response = await client.chat.completions.create({
            model: "llama-3.3-70b-versatile",
            messages: [{ role: "user", content: prompt }],
            response_format: { type: "json_object" },
            temperature: 0.9 
        });

        const text = response.choices[0]?.message?.content || "{}";
        return JSON.parse(text);

    } catch (e) {
        console.error("AI Category Gen Error:", e);
        return {
            title: "Focus Flow",
            description: "Generated by fallback",
            filterType: "keyword", 
            filterParams: { keyword: "e" } 
        };
    }
}

export const generateWrappedStory = async (period: string): Promise<any> => {
     try {
        const client = getAiClient();
        if (!client) throw new Error("No API Key");

        const prompt = `
            Write a short, engaging, "Spotify Wrapped" style story text for a user's listening history for the ${period}.
            Make it fun, personalized, and exciting.
            Return ONLY a JSON object:
            {
                "storyTitle": "Your ${period} in Review",
                "storyText": "You really loved...",
                "topGenre": "Pop",
                "listeningMinutes": 12050
            }
        `;
         
        const response = await client.chat.completions.create({
            model: "llama-3.3-70b-versatile",
            messages: [{ role: "user", content: prompt }],
            response_format: { type: "json_object" },
            temperature: 0.7
        });
        
        const text = response.choices[0]?.message?.content || "{}";
        return JSON.parse(text);

     } catch (e) {
         console.error("Groq Wrapped Error:", e);
         return {
             storyTitle: `Your ${period} Recap`,
             storyText: "You listened to some great music!",
             topGenre: "Mixed",
             listeningMinutes: 0
         }
     }
}
