import React, { useRef, useEffect, useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { AlertTriangle, RefreshCcw, Maximize2, Minimize2 } from 'lucide-react';

interface CanvasRendererProps {
    html: string;
    title: string;
    description: string;
    retryCount?: number;
    error?: string;
    onRetry?: () => void;
    maxRetries?: number;
}

export const CanvasRenderer: React.FC<CanvasRendererProps> = ({
    html,
    title,
    description,
    retryCount = 0,
    error,
    onRetry,
    maxRetries = 5
}) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const [renderError, setRenderError] = useState<string | null>(error || null);
    const [contentHeight, setContentHeight] = useState(400);
    const [expanded, setExpanded] = useState(false);
    const [loaded, setLoaded] = useState(false);

    const canRetry = retryCount < maxRetries && !!onRetry;

    // Extract body content from HTML
    const extractBodyContent = (htmlString: string): { styles: string; scripts: string; body: string } => {
        const parser = new DOMParser();
        const doc = parser.parseFromString(htmlString, 'text/html');
        
        // Extract styles
        const styleElements = doc.querySelectorAll('style');
        const styles = Array.from(styleElements).map(s => s.textContent || '').join('\n');
        
        // Extract scripts
        const scriptElements = doc.querySelectorAll('script');
        const scripts = Array.from(scriptElements).map(s => s.textContent || '').join('\n');
        
        // Extract body content
        const bodyContent = doc.body ? doc.body.innerHTML : htmlString;
        
        return { styles, scripts, body: bodyContent };
    };

    // Inject HTML content directly into the DOM
    // NOTE: This renders AI-generated HTML from a trusted source (canvasService).
    // The HTML is generated by Groq AI and contains only visualization code.
    // This replaces the previous iframe implementation to avoid cross-origin errors.
    const renderContent = useCallback(() => {
        if (!containerRef.current || !html) return;

        try {
            setRenderError(null);
            setLoaded(false);

            const container = containerRef.current;
            
            // Clear previous content
            container.innerHTML = '';
            
            // Extract content from HTML
            const { styles, scripts, body } = extractBodyContent(html);
            
            // Create a wrapper div for the content with app-consistent styling
            const contentWrapper = document.createElement('div');
            contentWrapper.style.cssText = 'margin: 0; padding: 16px; background: #0a0a0a; color: #fff; font-family: -apple-system, BlinkMacSystemFont, "SF Pro Display", "Segoe UI", sans-serif; min-height: 100px;';
            
            // Add styles to the wrapper (scoped to this component)
            if (styles) {
                const styleElement = document.createElement('style');
                styleElement.textContent = styles;
                contentWrapper.appendChild(styleElement);
            }
            
            // Add body content (from trusted AI-generated HTML)
            const bodyDiv = document.createElement('div');
            bodyDiv.innerHTML = body;
            contentWrapper.appendChild(bodyDiv);
            
            // Add to container
            container.appendChild(contentWrapper);
            
            // Execute scripts after content is rendered (trusted AI-generated code)
            // Scripts are from the AI service and typically contain visualization logic
            if (scripts) {
                try {
                    // Wrap script in error handler to prevent crashes
                    const wrappedScript = `
                        try {
                            ${scripts}
                        } catch (err) {
                            console.error('Canvas script error:', err);
                        }
                    `;
                    const scriptElement = document.createElement('script');
                    scriptElement.textContent = wrappedScript;
                    contentWrapper.appendChild(scriptElement);
                } catch (scriptErr: any) {
                    console.error('Failed to execute canvas scripts:', scriptErr);
                }
            }
            
            // Wait for content to render before calculating height
            // Timeout allows DOM to settle and scripts to run
            setTimeout(() => {
                setLoaded(true);
                // Calculate content height with constraints:
                // - Minimum 100px for small content
                // - Add 32px padding for scrollbars/spacing
                // - Cap at 800px to prevent excessive heights
                const height = contentWrapper.scrollHeight;
                const MIN_HEIGHT = 100;
                const PADDING = 32;
                const MAX_HEIGHT = 800;
                if (height > MIN_HEIGHT) {
                    setContentHeight(Math.min(height + PADDING, MAX_HEIGHT));
                }
            }, 100); // 100ms is sufficient for most visualizations to initialize

        } catch (err: any) {
            setRenderError(err.message || 'Failed to render component');
            setLoaded(true);
        }
    }, [html]);

    // Render when html changes
    useEffect(() => {
        if (html) {
            renderContent();
        }
    }, [html, renderContent]);

    // Error state - no HTML or generation failed
    if (!html || error) {
        return (
            <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className="w-full max-w-2xl mx-auto"
            >
                <div className="bg-[#1C1C1E] border border-red-500/20 rounded-2xl p-6 text-center">
                    <AlertTriangle className="w-8 h-8 text-red-400 mx-auto mb-3" />
                    <p className="text-red-400 text-sm font-medium mb-1">Component Generation Failed</p>
                    <p className="text-[#8E8E93] text-xs mb-4">{error || renderError || 'Unknown error'}</p>
                    {retryCount > 0 && (
                        <p className="text-[#666] text-xs mb-3">Attempted {retryCount} of {maxRetries} retries</p>
                    )}
                    {canRetry && (
                        <button
                            onClick={onRetry}
                            className="px-5 py-2 bg-[#FA2D48] text-white rounded-lg text-sm font-semibold hover:brightness-110 transition-all flex items-center gap-2 mx-auto"
                        >
                            <RefreshCcw size={14} /> Try Again
                        </button>
                    )}
                </div>
            </motion.div>
        );
    }

    return (
        <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="w-full max-w-2xl mx-auto"
        >
            <div className="bg-[#1C1C1E] border border-white/10 rounded-2xl overflow-hidden shadow-xl">
                {/* Header */}
                <div className="flex items-center justify-between px-4 py-3 border-b border-white/5 bg-[#1C1C1E]">
                    <div className="flex items-center gap-3 min-w-0">
                        <div className="flex gap-1.5">
                            <span className="w-3 h-3 rounded-full bg-[#FF5F57]" />
                            <span className="w-3 h-3 rounded-full bg-[#FEBC2E]" />
                            <span className="w-3 h-3 rounded-full bg-[#28C840]" />
                        </div>
                        <div className="min-w-0">
                            <h4 className="text-white text-sm font-semibold truncate">{title}</h4>
                            {description && (
                                <p className="text-[#8E8E93] text-[11px] truncate">{description}</p>
                            )}
                        </div>
                    </div>
                    <div className="flex items-center gap-2">
                        {retryCount > 0 && (
                            <span className="text-[10px] text-[#666] bg-white/5 px-2 py-1 rounded-full">
                                Retry #{retryCount}
                            </span>
                        )}
                        <button
                            onClick={() => setExpanded(!expanded)}
                            className="p-1.5 rounded-lg text-[#8E8E93] hover:text-white hover:bg-white/10 transition-all"
                        >
                            {expanded ? <Minimize2 size={14} /> : <Maximize2 size={14} />}
                        </button>
                    </div>
                </div>

                {/* Render Error Banner */}
                {renderError && (
                    <div className="px-4 py-2 bg-red-500/10 border-b border-red-500/20 flex items-center gap-2">
                        <AlertTriangle size={12} className="text-red-400 flex-shrink-0" />
                        <p className="text-red-400 text-xs truncate">{renderError}</p>
                        {canRetry && (
                            <button
                                onClick={onRetry}
                                className="ml-auto text-xs text-red-400 hover:text-red-300 underline flex-shrink-0"
                            >
                                Retry
                            </button>
                        )}
                    </div>
                )}

                {/* Loading overlay */}
                {!loaded && !renderError && (
                    <div className="flex items-center justify-center py-8">
                        <div className="flex items-center gap-2 text-[#8E8E93] text-sm">
                            <RefreshCcw size={14} className="animate-spin" />
                            Rendering...
                        </div>
                    </div>
                )}

                {/* Content Container */}
                <div
                    ref={containerRef}
                    className="w-full border-0 bg-[#0a0a0a] transition-all duration-300 overflow-auto"
                    style={{
                        height: expanded ? '80vh' : `${contentHeight}px`,
                        display: loaded || renderError ? 'block' : 'none'
                    }}
                />
            </div>
        </motion.div>
    );
};
